//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public BangLuong()
        {
            this.CT_LuongCTV = new HashSet<CT_LuongCTV>();
        }
    
        public string MaBangLuong { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> ThangTinhLuong { get; set; }
        public Nullable<int> NamTinhLuong { get; set; }
        public Nullable<int> TongTienLuong { get; set; }
    
        public virtual ICollection<CT_LuongCTV> CT_LuongCTV { get; set; }
    }
}
