//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapBacKH
    {
        public CapBacKH()
        {
            this.KhachHang = new HashSet<KhachHang>();
            this.PhieuUuDai = new HashSet<PhieuUuDai>();
        }
    
        public string MaCapBac { get; set; }
        public string TenCapBac { get; set; }
        public Nullable<int> DiemToiThieu { get; set; }
        public Nullable<double> HeSoNhan { get; set; }
    
        public virtual ICollection<KhachHang> KhachHang { get; set; }
        public virtual ICollection<PhieuUuDai> PhieuUuDai { get; set; }
    }
}
