//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTacVien
    {
        public CongTacVien()
        {
            this.CT_LuongCTV = new HashSet<CT_LuongCTV>();
            this.DonDatDV = new HashSet<DonDatDV>();
            this.LichLamViec = new HashSet<LichLamViec>();
            this.YeuCauDoiCTV = new HashSet<YeuCauDoiCTV>();
            this.KhachHang = new HashSet<KhachHang>();
        }
    
        public string MaCTV { get; set; }
        public string TenCTV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string TrinhDo { get; set; }
        public string KinhNghiem { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public string MaDonDKCTV { get; set; }
        public string AnhCTV { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
    
        public virtual DonDangKyCTV DonDangKyCTV { get; set; }
        public virtual ICollection<CT_LuongCTV> CT_LuongCTV { get; set; }
        public virtual ICollection<DonDatDV> DonDatDV { get; set; }
        public virtual ICollection<LichLamViec> LichLamViec { get; set; }
        public virtual ICollection<YeuCauDoiCTV> YeuCauDoiCTV { get; set; }
        public virtual ICollection<KhachHang> KhachHang { get; set; }
    }
}
