//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_LuongCTV
    {
        public string MaBangLuong { get; set; }
        public string MaCTV { get; set; }
        public Nullable<int> SoGioLam { get; set; }
        public string MaKhenThuong { get; set; }
        public Nullable<int> ThucLanh { get; set; }
    
        public virtual BangLuong BangLuong { get; set; }
        public virtual CongTacVien CongTacVien { get; set; }
    }
}
