<?xml version="1.0" encoding="utf-8"?><Database Name="GiupViecNhaDB" Class="DBGiupViecNhaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HungTran;Initial Catalog=GiupViecNhaDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="GiupViecNhaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ThongKe" Member="ThongKes">
    <Type Name="ThongKe">
      <Column Name="MaThongKe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayThongKe" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LoaiThongKe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThongKe_ChiTietThongKe" Member="ChiTietThongKes" ThisKey="MaThongKe" OtherKey="MaThongKe" Type="ChiTietThongKe" />
    </Type>
  </Table>
  <Table Name="dbo.BangLuong" Member="BangLuongs">
    <Type Name="BangLuong">
      <Column Name="MaBangLuong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThangTinhLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamTinhLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTienLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BangLuong_CT_LuongCTV" Member="CT_LuongCTVs" ThisKey="MaBangLuong" OtherKey="MaBangLuong" Type="CT_LuongCTV" />
    </Type>
  </Table>
  <Table Name="dbo.CapBacKH" Member="CapBacKHs">
    <Type Name="CapBacKH">
      <Column Name="MaCapBac" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCapBac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemToiThieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemToiDa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CapBacKH_KhachHang" Member="KhachHangs" ThisKey="MaCapBac" OtherKey="MaCapBacKH" Type="KhachHang" />
      <Association Name="CapBacKH_PhieuUuDai" Member="PhieuUuDais" ThisKey="MaCapBac" OtherKey="MaCapBac" Type="PhieuUuDai" />
    </Type>
  </Table>
  <Table Name="dbo.CongTacVien" Member="CongTacViens">
    <Type Name="CongTacVien">
      <Column Name="MaCTV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCTV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="KinhNghiem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemDanhGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDonDKCTV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="CongTacVien_CT_LuongCTV" Member="CT_LuongCTVs" ThisKey="MaCTV" OtherKey="MaCTV" Type="CT_LuongCTV" />
      <Association Name="CongTacVien_DonDatDV" Member="DonDatDVs" ThisKey="MaCTV" OtherKey="MaCTVNhanViec" Type="DonDatDV" />
      <Association Name="CongTacVien_DSCTVYeuThich" Member="DSCTVYeuThiches" ThisKey="MaCTV" OtherKey="MaCTV" Type="DSCTVYeuThich" />
      <Association Name="CongTacVien_LichLamViec" Member="LichLamViecs" ThisKey="MaCTV" OtherKey="MaCTV" Type="LichLamViec" />
      <Association Name="DonDangKyCTV_CongTacVien" Member="DonDangKyCTV" ThisKey="MaDonDKCTV" OtherKey="MaDon" Type="DonDangKyCTV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_LuongCTV" Member="CT_LuongCTVs">
    <Type Name="CT_LuongCTV">
      <Column Name="MaBangLuong" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCTV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoGioLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhenThuong" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ThucLanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BangLuong_CT_LuongCTV" Member="BangLuong" ThisKey="MaBangLuong" OtherKey="MaBangLuong" Type="BangLuong" IsForeignKey="true" />
      <Association Name="CongTacVien_CT_LuongCTV" Member="CongTacVien" ThisKey="MaCTV" OtherKey="MaCTV" Type="CongTacVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietThongKe" Member="ChiTietThongKes">
    <Type Name="ChiTietThongKe">
      <Column Name="MaThongKe" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDonDat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThongKe_ChiTietThongKe" Member="ThongKe" ThisKey="MaThongKe" OtherKey="MaThongKe" Type="ThongKe" IsForeignKey="true" />
      <Association Name="DonDatDV_ChiTietThongKe" Member="DonDatDV" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="DonDatDV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="MaDichVu" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GiaThanh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KinhNghiemYeuCau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiDV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="DichVu_DonDatDV" Member="DonDatDVs" ThisKey="MaDichVu" OtherKey="MaDV" Type="DonDatDV" />
      <Association Name="DichVu_PhieuUuDai" Member="PhieuUuDais" ThisKey="MaDichVu" OtherKey="MaDichVu" Type="PhieuUuDai" />
      <Association Name="LoaiDV_DichVu" Member="LoaiDV1" ThisKey="LoaiDV" OtherKey="MaLoaiDV" Type="LoaiDV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatDV" Member="DonDatDVs">
    <Type Name="DonDatDV">
      <Column Name="MaDonDat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoThoiGianThue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiaChiThucHien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianThucHien" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MoTaCongViec" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KinhNghiemYeuCau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangDonDat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaCTVNhanViec" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TuyChonCTV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HinhThucThanhToan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrangThanhToan" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ChiPhiPhatSinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaUuDaiApDung" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="DonDatDV_ChiTietThongKe" Member="ChiTietThongKes" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="ChiTietThongKe" />
      <Association Name="DonDatDV_HoaDonDV" Member="HoaDonDVs" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="HoaDonDV" />
      <Association Name="DonDatDV_LichLamViec" Member="LichLamViecs" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="LichLamViec" />
      <Association Name="CongTacVien_DonDatDV" Member="CongTacVien" ThisKey="MaCTVNhanViec" OtherKey="MaCTV" Type="CongTacVien" IsForeignKey="true" />
      <Association Name="DichVu_DonDatDV" Member="DichVu" ThisKey="MaDV" OtherKey="MaDichVu" Type="DichVu" IsForeignKey="true" />
      <Association Name="PhieuUuDai_DonDatDV" Member="PhieuUuDai" ThisKey="MaUuDaiApDung" OtherKey="MaUuDai" Type="PhieuUuDai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DSCTVYeuThich" Member="DSCTVYeuThiches">
    <Type Name="DSCTVYeuThich">
      <Column Name="MaCTV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CongTacVien_DSCTVYeuThich" Member="CongTacVien" ThisKey="MaCTV" OtherKey="MaCTV" Type="CongTacVien" IsForeignKey="true" />
      <Association Name="KhachHang_DSCTVYeuThich" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDV" Member="HoaDonDVs">
    <Type Name="HoaDonDV">
      <Column Name="MaHoaDon" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDonDat" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonDatDV_HoaDonDV" Member="DonDatDV" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="DonDatDV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
      <Column Name="SoDiemThuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCapBacKH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="KhachHang_DSCTVYeuThich" Member="DSCTVYeuThiches" ThisKey="MaKH" OtherKey="MaKH" Type="DSCTVYeuThich" />
      <Association Name="KhachHang_KhachHang_UuDai" Member="KhachHang_UuDais" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang_UuDai" />
      <Association Name="CapBacKH_KhachHang" Member="CapBacKH" ThisKey="MaCapBacKH" OtherKey="MaCapBac" Type="CapBacKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang_UuDai" Member="KhachHang_UuDais">
    <Type Name="KhachHang_UuDai">
      <Column Name="MaUuDai" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KhachHang_KhachHang_UuDai" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="PhieuUuDai_KhachHang_UuDai" Member="PhieuUuDai" ThisKey="MaUuDai" OtherKey="MaUuDai" Type="PhieuUuDai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichLamViec" Member="LichLamViecs">
    <Type Name="LichLamViec">
      <Column Name="MaCTV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDonDat" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayLamViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoDiemDanhGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GopY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CongTacVien_LichLamViec" Member="CongTacVien" ThisKey="MaCTV" OtherKey="MaCTV" Type="CongTacVien" IsForeignKey="true" />
      <Association Name="DonDatDV_LichLamViec" Member="DonDatDV" ThisKey="MaDonDat" OtherKey="MaDonDat" Type="DonDatDV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDV" Member="LoaiDVs">
    <Type Name="LoaiDV">
      <Column Name="MaLoaiDV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiDV_DichVu" Member="DichVus" ThisKey="MaLoaiDV" OtherKey="LoaiDV" Type="DichVu" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuUuDai" Member="PhieuUuDais">
    <Type Name="PhieuUuDai">
      <Column Name="MaUuDai" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenUuDai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDiemCan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhanTramGiamGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCapBac" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaDichVu" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="PhieuUuDai_DonDatDV" Member="DonDatDVs" ThisKey="MaUuDai" OtherKey="MaUuDaiApDung" Type="DonDatDV" />
      <Association Name="PhieuUuDai_KhachHang_UuDai" Member="KhachHang_UuDais" ThisKey="MaUuDai" OtherKey="MaUuDai" Type="KhachHang_UuDai" />
      <Association Name="CapBacKH_PhieuUuDai" Member="CapBacKH" ThisKey="MaCapBac" OtherKey="MaCapBac" Type="CapBacKH" IsForeignKey="true" />
      <Association Name="DichVu_PhieuUuDai" Member="DichVu" ThisKey="MaDichVu" OtherKey="MaDichVu" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDangKyCTV" Member="DonDangKyCTVs">
    <Type Name="DonDangKyCTV">
      <Column Name="MaDon" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySInh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TrinhDoHocVan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KinhNghiem" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemKiemTra" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThaiDuyet" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DonDangKyCTV_CongTacVien" Member="CongTacViens" ThisKey="MaDon" OtherKey="MaDonDKCTV" Type="CongTacVien" />
    </Type>
  </Table>
</Database>