//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiupViecNhaDBEntities1 : DbContext
    {
        public GiupViecNhaDBEntities1()
            : base("name=GiupViecNhaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuong { get; set; }
        public virtual DbSet<CapBacKH> CapBacKH { get; set; }
        public virtual DbSet<CongTacVien> CongTacVien { get; set; }
        public virtual DbSet<CT_LuongCTV> CT_LuongCTV { get; set; }
        public virtual DbSet<ChiTietThongKe> ChiTietThongKe { get; set; }
        public virtual DbSet<DichVu> DichVu { get; set; }
        public virtual DbSet<DonDangKyCTV> DonDangKyCTV { get; set; }
        public virtual DbSet<DonDatDV> DonDatDV { get; set; }
        public virtual DbSet<HoaDonDV> HoaDonDV { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhachHang_UuDai> KhachHang_UuDai { get; set; }
        public virtual DbSet<LichLamViec> LichLamViec { get; set; }
        public virtual DbSet<LoaiDV> LoaiDV { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuUuDai> PhieuUuDai { get; set; }
        public virtual DbSet<ThongKe> ThongKe { get; set; }
        public virtual DbSet<YeuCauDoiCTV> YeuCauDoiCTV { get; set; }
    }
}
