//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDangKyCTV
    {
        public DonDangKyCTV()
        {
            this.CongTacVien = new HashSet<CongTacVien>();
        }
    
        public string MaDon { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySInh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string TrinhDoHocVan { get; set; }
        public string KinhNghiem { get; set; }
        public Nullable<double> DiemKiemTra { get; set; }
        public string TrangThaiDuyet { get; set; }
        public string AnhCTV { get; set; }
    
        public virtual ICollection<CongTacVien> CongTacVien { get; set; }
    }
}
