//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatDV
    {
        public DonDatDV()
        {
            this.ChiTietThongKe = new HashSet<ChiTietThongKe>();
            this.HoaDonDV = new HashSet<HoaDonDV>();
            this.LichLamViec = new HashSet<LichLamViec>();
            this.YeuCauDoiCTV = new HashSet<YeuCauDoiCTV>();
        }
    
        public string MaDonDat { get; set; }
        public string MaDV { get; set; }
        public Nullable<int> SoThoiGianThue { get; set; }
        public string DiaChiThucHien { get; set; }
        public Nullable<System.DateTime> ThoiGianThucHien { get; set; }
        public string MoTaCongViec { get; set; }
        public string KinhNghiemYeuCau { get; set; }
        public string TinhTrangDonDat { get; set; }
        public string MaKH { get; set; }
        public string MaCTVNhanViec { get; set; }
        public string TuyChonCTV { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string TinhTrangThanhToan { get; set; }
        public Nullable<int> ChiPhiChonCTV { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string MaUuDaiApDung { get; set; }
    
        public virtual CongTacVien CongTacVien { get; set; }
        public virtual ICollection<ChiTietThongKe> ChiTietThongKe { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuUuDai PhieuUuDai { get; set; }
        public virtual ICollection<HoaDonDV> HoaDonDV { get; set; }
        public virtual ICollection<LichLamViec> LichLamViec { get; set; }
        public virtual ICollection<YeuCauDoiCTV> YeuCauDoiCTV { get; set; }
    }
}
