//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang_UuDai
    {
        public string MaUuDai { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuUuDai PhieuUuDai { get; set; }
    }
}
