//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.KhachHang_UuDai = new HashSet<KhachHang_UuDai>();
            this.CongTacVien = new HashSet<CongTacVien>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> SoDiemThuong { get; set; }
        public string MaCapBacKH { get; set; }
    
        public virtual CapBacKH CapBacKH { get; set; }
        public virtual ICollection<KhachHang_UuDai> KhachHang_UuDai { get; set; }
        public virtual ICollection<CongTacVien> CongTacVien { get; set; }
    }
}
