//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public string MaCTV { get; set; }
        public string MaDonDat { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<int> SoDiemDanhGia { get; set; }
        public string GopY { get; set; }
    
        public virtual CongTacVien CongTacVien { get; set; }
        public virtual DonDatDV DonDatDV { get; set; }
    }
}
