//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDV
    {
        public LoaiDV()
        {
            this.DichVu = new HashSet<DichVu>();
        }
    
        public string MaLoaiDV { get; set; }
        public string TenLoaiDV { get; set; }
    
        public virtual ICollection<DichVu> DichVu { get; set; }
    }
}
