//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.ChucVu = new HashSet<ChucVu>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
         [Required(ErrorMessage = "*Bạn chưa nhập mật khẩu")]
        public string TenDN { get; set; }
         [Required(ErrorMessage = "*Bạn chưa nhập tên đăng nhập")]
        public string MatKhau { get; set; }
    
        public virtual ICollection<ChucVu> ChucVu { get; set; }
    }
}
