//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        [Required(ErrorMessage = ("*Không được bỏ trống email"))]
        public string Email { get; set; }
        [Required(ErrorMessage = ("*Không được bỏ trống mật khẩu"))]
        public string MatKhau { get; set; }
        public string ChucVu { get; set; }
    }
}
