//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenND
    {
        public string MaVaiTro { get; set; }
        public string MaChucNang { get; set; }
        public Nullable<bool> CoQuyen { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual ChucVu ChucVu { get; set; }
    }
}
