//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuUuDai
    {
        public PhieuUuDai()
        {
            this.DonDatDV = new HashSet<DonDatDV>();
            this.KhachHang_UuDai = new HashSet<KhachHang_UuDai>();
        }
    
        public string MaUuDai { get; set; }
        public string TenUuDai { get; set; }
        public Nullable<int> SoDiemCan { get; set; }
        public Nullable<int> PhanTramGiamGia { get; set; }
        public string MaCapBac { get; set; }
        public string MaDichVu { get; set; }
    
        public virtual CapBacKH CapBacKH { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual ICollection<DonDatDV> DonDatDV { get; set; }
        public virtual ICollection<KhachHang_UuDai> KhachHang_UuDai { get; set; }
    }
}
