//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKe
    {
        public ThongKe()
        {
            this.ChiTietThongKe = new HashSet<ChiTietThongKe>();
        }
    
        public string MaThongKe { get; set; }
        public Nullable<System.DateTime> NgayThongKe { get; set; }
        public string LoaiThongKe { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual ICollection<ChiTietThongKe> ChiTietThongKe { get; set; }
    }
}
