//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_GiupViecNha.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauDoiCTV
    {
        public string MaYC { get; set; }
        public string MaDonDat { get; set; }
        public Nullable<int> SoLanDoi { get; set; }
        public string CTVChonDoi { get; set; }
        public string TrangThaiDoi { get; set; }
    
        public virtual CongTacVien CongTacVien { get; set; }
        public virtual DonDatDV DonDatDV { get; set; }
    }
}
